<a href="https://colab.research.google.com/github/SMK-BTW/Twenty/blob/main/Machine_Learning_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## setup
installs the pinned versions so results are the same every run. on colab, restart the runtime once after this cell if it asks

In [1]:
%pip install -q numpy==2.1.3 pandas==2.2.3 scipy==1.14.1 scikit-learn==1.6.1 duckdb==1.1.3 pyarrow==18.1.0 huggingface_hub==0.26.5

Note: you may need to restart the kernel to use updated packages.

## initial exploration (proposal)

In [2]:
from huggingface_hub import hf_hub_url, hf_hub_download
import duckdb

C:\Users\Arbab\OneDrive\Desktop\Projects\ml_class_proj\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# download once at a fixed version, then read it locally
url = hf_hub_download(
    repo_id="yandex/yambda",
    filename="flat/50m/multi_event.parquet",
    repo_type="dataset",
    revision="dd6f3a19eef5866e346c3270e098baa641a44948",
    local_dir="data/raw"
)

In [4]:
con = duckdb.connect()

con.execute("INSTALL httpfs")
con.execute("LOAD httpfs")

In [5]:
df = con.execute(f"""
    SELECT *
    FROM read_parquet('{url}')
    USING SAMPLE reservoir(100000 ROWS) REPEATABLE (42)
""").df()

In [6]:
print(df.shape)
print("Unique users:", df["uid"].nunique())
print("Unique tracks:", df["item_id"].nunique())

print("\nEvent types:")
print(df["event_type"].value_counts())

(100000, 7)
Unique users: 8246
Unique tracks: 47696

Event types:
event_type
listen       97195
like          1826
unlike         704
dislike        235
undislike       40
Name: count, dtype: int64

In [7]:
df.head()

,uid,timestamp,item_id,is_organic,played_ratio_pct,track_length_seconds,event_type
0,493300,15857805,3061013,1,100.0,140.0,listen
1,124800,14547695,2211124,1,97.0,260.0,listen
2,380500,1881575,8371986,0,100.0,210.0,listen
3,792100,20513065,2632222,0,100.0,180.0,listen
4,292200,15526375,8240392,1,12.0,245.0,listen

In [8]:
df.isnull().sum()

uid                        0
timestamp                  0
item_id                    0
is_organic                 0
played_ratio_pct        2805
track_length_seconds    2805
event_type                 0
dtype: int64

played_ratio_pct is the percentage of track played (1-100)

In [9]:
listening_df = df[
    (df["event_type"] == "listen") &
    (df["played_ratio_pct"] > 50)
].copy()

In [10]:
print("Meaningful listening events:", len(listening_df))
print("Unique users:", listening_df["uid"].nunique())
print("Unique songs:", listening_df["item_id"].nunique())

Meaningful listening events: 61452
Unique users: 7306
Unique songs: 33584

We have meaningful listen data but the user might have listened to one track several times so we collapse them

In [11]:
interactions = (
    listening_df[
        ["uid", "item_id"]
    ]
    .drop_duplicates()
    .copy()
)

interactions["interaction"] = 1

interactions.head()

      uid  item_id  interaction
0  493300  3061013            1
1  124800  2211124            1
2  380500  8371986            1
3  792100  2632222            1
5   18300  8907903            1

In [12]:
print("User-song pairs:", len(interactions))
print("Users:", interactions["uid"].nunique())
print("Songs:", interactions["item_id"].nunique())

User-song pairs: 60456
Users: 7306
Songs: 33584

In [13]:
user_activity = (
    interactions.groupby("uid")
    .size()
    .sort_values(ascending=False)
)

user_activity.head(10)

uid
83700     61
370000    60
246000    57
997500    57
122600    54
316000    54
677500    52
151200    52
214900    52
917700    52
dtype: int64

In [14]:
target_user = user_activity.index[0]

print("Sample target user:", target_user)
print(
    "Number of unique songs:",
    user_activity.loc[target_user]
)

Sample target user: 83700
Number of unique songs: 61

Sample input Data for the proposal

In [15]:
sample_input = (
    listening_df[
        listening_df["uid"] == target_user
    ][
        [
            "uid",
            "timestamp",
            "item_id",
            "played_ratio_pct",
            "event_type"
        ]
    ]
    .head(10)
)

sample_input

         uid  timestamp  item_id  played_ratio_pct event_type
2500   83700    6087975  5259215             100.0     listen
2890   83700   21728470   706302             100.0     listen
3705   83700    7032210  5343191             100.0     listen
5223   83700   11789265  3261141             100.0     listen
8340   83700   13099760  1564537             100.0     listen
11479  83700   20419580  6818788             100.0     listen
12220  83700   14036595  2473593             100.0     listen
13570  83700     632630  8275755             100.0     listen
14509  83700    8857880  7065749             100.0     listen
21000  83700   22774495  3927423             100.0     listen

K-NN Model Input

In [16]:
sample_model_input = interactions[
    interactions["uid"] == target_user
].copy()

sample_model_input.head(10)

         uid  item_id  interaction
2500   83700  5259215            1
2890   83700   706302            1
3705   83700  5343191            1
5223   83700  3261141            1
8340   83700  1564537            1
11479  83700  6818788            1
12220  83700  2473593            1
13570  83700  8275755            1
14509  83700  7065749            1
21000  83700  3927423            1

In [17]:
OUTPUT_COLUMNS = [
    "uid",
    "rank",
    "item_id",
    "score"
]

print("Expected recommender output columns:")
print(OUTPUT_COLUMNS)

Expected recommender output columns:
['uid', 'rank', 'item_id', 'score']

In [18]:
already_listened = set(
    interactions.loc[
        interactions["uid"] == target_user,
        "item_id"
    ]
)

print("Target user:", target_user)
print("Songs already listened to:", len(already_listened))

Target user: 83700
Songs already listened to: 61

In [19]:
def validate_recommendations(
    recommendations,
    already_listened
):
    overlap = set(
        recommendations["item_id"]
    ).intersection(already_listened)


    if len(overlap) > 0:
        return f"Invalid - overlapping songs: {overlap}"
    else:
        return "Valid"

## baseline pipeline
full listens file, split by time, tune knn on validation, score both models on test

In [20]:
import numpy as np
import pandas as pd
import scipy.sparse as sp
from sklearn import config_context
from sklearn.neighbors import NearestNeighbors

DAY, GAP = 86_400, 30 * 60

path = hf_hub_download("yandex/yambda", "flat/50m/listens.parquet", repo_type="dataset",
                       revision="dd6f3a19eef5866e346c3270e098baa641a44948", local_dir="data/raw")

# one row per user and song, first listen with more than 50% played
pairs = duckdb.sql(f"""
    SELECT uid, item_id, min(timestamp) AS ts, arg_min(is_organic, timestamp) AS is_organic
    FROM '{str(path).replace(chr(92), "/")}'
    WHERE played_ratio_pct > 50
    GROUP BY uid, item_id
""").df()
print(f"{len(pairs):,} pairs, {pairs.uid.nunique():,} users, {pairs.item_id.nunique():,} songs")

9,019,829 pairs, 9,207 users, 630,139 songs

### split
same cutoff for every user: `| train |gap| val (7d) |gap| test (7d) |`

val is used to pick k, then train + val -> test gives the reported numbers. songs need 20+ listeners in train

In [21]:
def make_split(train_end, test_start, test_end):
    train = pairs[pairs.ts < train_end]
    test = pairs[(pairs.ts >= test_start) & (pairs.ts < test_end)]
    counts = train.item_id.value_counts()
    items = np.sort(counts[counts >= 20].index.to_numpy())
    train = train[train.item_id.isin(items)]
    users = np.sort(train.uid.unique())
    X = sp.csr_matrix((np.ones(len(train), np.float32),
                       (np.searchsorted(users, train.uid), np.searchsorted(items, train.item_id))),
                      shape=(len(users), len(items)))
    test = test[test.uid.isin(users)]
    targets = test.groupby("uid").item_id.apply(set)
    by_flag = lambda f: list(test[test.is_organic == f].groupby("uid").item_id.apply(set)
                             .reindex(targets.index).apply(lambda t: t if isinstance(t, set) else set()))
    return {"X": X, "items": items, "eval_users": np.searchsorted(users, targets.index),
            "targets": list(targets), "organic": by_flag(1), "nonorganic": by_flag(0),
            "in_catalog": test.item_id.isin(items).mean()}


t_end = pairs.ts.max() + 1
test_start = t_end - 7 * DAY
val_start = test_start - GAP - 7 * DAY
val = make_split(val_start - GAP, val_start, test_start - GAP)
test = make_split(test_start - GAP, test_start, t_end)
for name, d in [("val", val), ("test", test)]:
    print(f"{name}: {d['X'].shape[0]:,} users x {d['X'].shape[1]:,} songs, {d['X'].nnz:,} train pairs, "
          f"{len(d['eval_users']):,} eval users, {100 * d['in_catalog']:.2f}% of held-out songs in catalog")

val: 9,155 users x 66,135 songs, 6,817,677 train pairs, 7,336 eval users, 71.78% of held-out songs in catalog
test: 9,175 users x 67,931 songs, 7,069,539 train pairs, 7,202 eval users, 72.92% of held-out songs in catalog

### models
- **MostPopular** (naive): songs with the most listeners in train
- **ItemKNN** (baseline): each song keeps its k most cosine similar songs, a song's score is the sum of its similarity to the user's songs

both skip songs the user already heard

In [22]:
def recommend(score_fn, X, rows, n=50):
    out = []
    for s in range(0, len(rows), 256):
        Xu = X[rows[s:s + 256]]
        scores = score_fn(Xu)
        scores[Xu.nonzero()] = -np.inf
        top = np.argpartition(-scores, n - 1, axis=1)[:, :n]
        order = np.argsort(-np.take_along_axis(scores, top, 1), axis=1, kind="stable")
        out.append(np.take_along_axis(top, order, 1))
    return np.vstack(out)


def most_popular(X):
    pop = np.asarray(X.sum(0)).ravel() - np.arange(X.shape[1]) * 1e-7  # ties -> lower index first
    return lambda Xu: np.tile(pop, (Xu.shape[0], 1))


def item_knn(X, k):
    items = X.T.tocsr()
    n = items.shape[0]
    nn = NearestNeighbors(n_neighbors=k + 1, metric="cosine", algorithm="brute", n_jobs=4).fit(items)
    with config_context(working_memory=256):
        dist, idx = nn.kneighbors(items)
    rows, cols, sim = np.repeat(np.arange(n), k + 1), idx.ravel(), (1 - dist).astype(np.float32).ravel()
    keep = (cols != rows) & (sim > 0)
    S = sp.csr_matrix((sim[keep], (rows[keep], cols[keep])), shape=(n, n))
    pop = np.asarray(X.sum(0)).ravel()
    tiebreak = (1e-6 * pop / pop.max()).astype(np.float32)  # only matters for ties
    return lambda Xu: (Xu @ S).toarray() + tiebreak

### metrics
precision, recall, ndcg, hit rate and catalog coverage at 10 and 50. also runs `validate_recommendations` from above on 500 users

In [23]:
def hits_ndcg(d, recs, k):
    hits = np.array([np.isin(r, list(t)) for r, t in zip(d["items"][recs[:, :k]], d["targets"])], float)
    disc = 1 / np.log2(np.arange(2, k + 2))
    ideal = np.array([disc[:min(len(t), k)].sum() for t in d["targets"]])
    return hits, (hits * disc).sum(1) / ideal


def evaluate(d, recs):
    for u, r in zip(d["eval_users"][:500], recs[:500]):
        assert validate_recommendations(pd.DataFrame({"item_id": r}), set(d["X"][u].indices)) == "Valid"
    res, n_targets = {}, np.array([len(t) for t in d["targets"]])
    for k in (10, 50):
        hits, ndcg = hits_ndcg(d, recs, k)
        res |= {f"precision@{k}": hits.sum(1).mean() / k, f"recall@{k}": (hits.sum(1) / n_targets).mean(),
                f"ndcg@{k}": ndcg.mean(), f"hitrate@{k}": (hits.sum(1) > 0).mean(),
                f"coverage@{k}": len(np.unique(recs[:, :k])) / len(d["items"])}
    return res

### tune k on validation

In [24]:
run = lambda d, model: recommend(model, d["X"], d["eval_users"])
ks = [20, 50, 100, 200]
tuning = pd.DataFrame([{"model": f"ItemKNN k={k}", **evaluate(val, run(val, item_knn(val["X"], k)))} for k in ks]
                      + [{"model": "MostPopular", **evaluate(val, run(val, most_popular(val["X"])))}])
best_k = ks[tuning["ndcg@10"][:len(ks)].argmax()]
print("best k:", best_k)
tuning.round(4)

best k: 20

,model,precision@10,recall@10,ndcg@10,hitrate@10,coverage@10,precision@50,recall@50,ndcg@50,hitrate@50,coverage@50
0,ItemKNN k=20,0.0286,0.0116,0.0310,0.1780,0.1254,0.0233,0.0426,0.0364,0.4321,0.3437
1,ItemKNN k=50,0.0277,0.0107,0.0302,0.1715,0.1088,0.0226,0.0396,0.0346,0.3993,0.2895
2,ItemKNN k=100,0.0274,0.0107,0.0302,0.1716,0.0996,0.0218,0.0369,0.0335,0.3835,0.2590
3,ItemKNN k=200,0.0281,0.0106,0.0310,0.1731,0.0942,0.0213,0.0362,0.0333,0.3772,0.2390
4,MostPopular,0.0163,0.0073,0.0191,0.0999,0.0023,0.0109,0.0193,0.0184,0.2192,0.0055

### baseline table (test)

In [25]:
recs = {"MostPopular": run(test, most_popular(test["X"])),
        f"ItemKNN-cosine (k={best_k})": run(test, item_knn(test["X"], best_k))}
table = pd.DataFrame([{"model": m, **evaluate(test, r)} for m, r in recs.items()])
table.round(4)

,model,precision@10,recall@10,ndcg@10,hitrate@10,coverage@10,precision@50,recall@50,ndcg@50,hitrate@50,coverage@50
0,MostPopular,0.0133,0.0067,0.0151,0.0878,0.0023,0.0092,0.0179,0.0158,0.2026,0.0054
1,ItemKNN-cosine (k=20),0.0272,0.0116,0.0299,0.1733,0.1169,0.0219,0.0427,0.0354,0.4218,0.3275

### diagnostics
why the models differ: user activity (training songs, split in thirds), organic vs non organic songs, popularity bias

In [26]:
hist = np.diff(test["X"].indptr)[test["eval_users"]]
bucket = pd.qcut(hist, 3, labels=["light", "medium", "heavy"])
print(pd.Series(hist).groupby(bucket, observed=True).agg(["min", "max"]))
pct = pd.Series(np.asarray(test["X"].sum(0)).ravel()).rank(pct=True).to_numpy()

diag = {}
for m, r in recs.items():
    hits, ndcg = hits_ndcg(test, r, 10)
    top = test["items"][r[:, :10]]
    row = {}
    for b in ["light", "medium", "heavy"]:
        row[f"ndcg@10_{b}"], row[f"hitrate@10_{b}"] = ndcg[bucket == b].mean(), hits.any(1)[bucket == b].mean()
    for name in ["organic", "nonorganic"]:
        tg = test[name]
        row[f"recall@10_{name}"] = sum(len(t & set(i)) for i, t in zip(top, tg)) / sum(len(t) for t in tg)
    row["mean_pop_percentile@10"] = pct[r[:, :10]].mean()
    row["head10pct_share@10"] = (pct[r[:, :10]] >= 0.9).mean()
    row["unique_items@10"] = len(np.unique(r[:, :10]))
    diag[m] = row
pd.DataFrame(diag).round(4)

        min   max
light     1   401
medium  402   992
heavy   993  6255

                        MostPopular  ItemKNN-cosine (k=20)
ndcg@10_light                0.0213                 0.0420
hitrate@10_light             0.1033                 0.2041
ndcg@10_medium               0.0134                 0.0272
hitrate@10_medium            0.0783                 0.1646
ndcg@10_heavy                0.0108                 0.0203
hitrate@10_heavy             0.0816                 0.1512
recall@10_organic            0.0053                 0.0076
recall@10_nonorganic         0.0027                 0.0069
mean_pop_percentile@10       0.9998                 0.9150
head10pct_share@10           1.0000                 0.7951
unique_items@10            154.0000              7944.0000