<a href="https://colab.research.google.com/github/SMK-BTW/Twenty/blob/main/Machine_Learning_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## setup
installs the pinned versions so results are the same every run. on colab, restart the runtime once after this cell if it asks

In [1]:
%pip install -q numpy==2.1.3 pandas==2.2.3 scipy==1.14.1 scikit-learn==1.6.1 duckdb==1.1.3 pyarrow==18.1.0 huggingface_hub==0.26.5 tabulate==0.9.0

Note: you may need to restart the kernel to use updated packages.

## initial exploration (proposal)

In [2]:
from huggingface_hub import hf_hub_url, hf_hub_download
import duckdb

C:\Users\Arbab\OneDrive\Desktop\Projects\ml_class_proj\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# download once at a fixed version, then read it locally
url = hf_hub_download(
    repo_id="yandex/yambda",
    filename="flat/50m/multi_event.parquet",
    repo_type="dataset",
    revision="dd6f3a19eef5866e346c3270e098baa641a44948",
    local_dir="data/raw"
)

In [4]:
con = duckdb.connect()

con.execute("INSTALL httpfs")
con.execute("LOAD httpfs")

In [5]:
df = con.execute(f"""
    SELECT *
    FROM read_parquet('{url}')
    USING SAMPLE reservoir(100000 ROWS) REPEATABLE (42)
""").df()

In [6]:
print(df.shape)
print("Unique users:", df["uid"].nunique())
print("Unique tracks:", df["item_id"].nunique())

print("\nEvent types:")
print(df["event_type"].value_counts())

(100000, 7)
Unique users: 8201
Unique tracks: 47945

Event types:
event_type
listen       97223
like          1830
unlike         662
dislike        223
undislike       62
Name: count, dtype: int64

In [7]:
df.head()

,uid,timestamp,item_id,is_organic,played_ratio_pct,track_length_seconds,event_type
0,465800,10173615,4803178,1,100.0,245.0,listen
1,76400,23628665,6155741,1,100.0,175.0,listen
2,370000,24262910,4179513,1,100.0,245.0,listen
3,782200,8324570,4306316,0,43.0,240.0,listen
4,326500,15350815,2978658,0,25.0,235.0,listen

In [8]:
df.isnull().sum()

uid                        0
timestamp                  0
item_id                    0
is_organic                 0
played_ratio_pct        2777
track_length_seconds    2777
event_type                 0
dtype: int64

played_ratio_pct is the percentage of track played (1-100)

In [9]:
listening_df = df[
    (df["event_type"] == "listen") &
    (df["played_ratio_pct"] > 50)
].copy()

In [10]:
print("Meaningful listening events:", len(listening_df))
print("Unique users:", listening_df["uid"].nunique())
print("Unique songs:", listening_df["item_id"].nunique())

Meaningful listening events: 61700
Unique users: 7306
Unique songs: 33890

We have meaningful listen data but the user might have listened to one track several times so we collapse them

In [11]:
interactions = (
    listening_df[
        ["uid", "item_id"]
    ]
    .drop_duplicates()
    .copy()
)

interactions["interaction"] = 1

interactions.head()

      uid  item_id  interaction
0  465800  4803178            1
1   76400  6155741            1
2  370000  4179513            1
5   18200  4120789            1
7  581900  8317228            1

In [12]:
print("User-song pairs:", len(interactions))
print("Users:", interactions["uid"].nunique())
print("Songs:", interactions["item_id"].nunique())

User-song pairs: 60702
Users: 7306
Songs: 33890

In [13]:
user_activity = (
    interactions.groupby("uid")
    .size()
    .sort_values(ascending=False)
)

user_activity.head(10)

uid
416400    67
330800    62
299100    58
650600    57
83700     54
122600    53
997500    53
276400    53
603700    53
727600    53
dtype: int64

In [14]:
target_user = user_activity.index[0]

print("Sample target user:", target_user)
print(
    "Number of unique songs:",
    user_activity.loc[target_user]
)

Sample target user: 416400
Number of unique songs: 67

Sample input Data for the proposal

In [15]:
sample_input = (
    listening_df[
        listening_df["uid"] == target_user
    ][
        [
            "uid",
            "timestamp",
            "item_id",
            "played_ratio_pct",
            "event_type"
        ]
    ]
    .head(10)
)

sample_input

         uid  timestamp  item_id  played_ratio_pct event_type
1482  416400   10818395   616002             100.0     listen
2167  416400   20077155  2007612             100.0     listen
2591  416400   16496745  2217061             100.0     listen
4988  416400   13265310  4093576             100.0     listen
5888  416400   15185145  8992229             100.0     listen
6136  416400   25458805  4405839             100.0     listen
6893  416400   15517520  4787710             100.0     listen
7149  416400    9825905  1841728             100.0     listen
8270  416400   17079405  1009607             100.0     listen
8311  416400   21669315  9040711             100.0     listen

K-NN Model Input

In [16]:
sample_model_input = interactions[
    interactions["uid"] == target_user
].copy()

sample_model_input.head(10)

         uid  item_id  interaction
1482  416400   616002            1
2167  416400  2007612            1
2591  416400  2217061            1
4988  416400  4093576            1
5888  416400  8992229            1
6136  416400  4405839            1
6893  416400  4787710            1
7149  416400  1841728            1
8270  416400  1009607            1
8311  416400  9040711            1

In [17]:
OUTPUT_COLUMNS = [
    "uid",
    "rank",
    "item_id",
    "score"
]

print("Expected recommender output columns:")
print(OUTPUT_COLUMNS)

Expected recommender output columns:
['uid', 'rank', 'item_id', 'score']

In [18]:
already_listened = set(
    interactions.loc[
        interactions["uid"] == target_user,
        "item_id"
    ]
)

print("Target user:", target_user)
print("Songs already listened to:", len(already_listened))

Target user: 416400
Songs already listened to: 67

In [19]:
def validate_recommendations(
    recommendations,
    already_listened
):
    overlap = set(
        recommendations["item_id"]
    ).intersection(already_listened)


    if len(overlap) > 0:
        return f"Invalid - overlapping songs: {overlap}"
    else:
        return "Valid"

## baseline pipeline
everything below is the reproducible baseline. it uses the full listens file (not the 100k sample above), splits by time, tunes knn on validation and scores both models on test

In [20]:
import json
import platform
import time
from pathlib import Path

import duckdb
import numpy as np
import pandas as pd
import scipy
import scipy.sparse as sp
import sklearn
from huggingface_hub import hf_hub_download
from sklearn import config_context
from sklearn.neighbors import NearestNeighbors

PROJECT_ROOT = Path.cwd()
DAY = 86_400  # seconds in a day

CFG = {
    # data source
    "hf_repo": "yandex/yambda",
    "hf_file": "flat/50m/listens.parquet",
    "hf_revision": "dd6f3a19eef5866e346c3270e098baa641a44948",
    "raw_dir": PROJECT_ROOT / "data" / "raw",
    "processed_dir": PROJECT_ROOT / "data" / "processed",
    "results_dir": PROJECT_ROOT / "results",
    # min percent of song played to count
    "min_played_ratio_pct": 50,
    # fraction of users to use (1.0 = all), set to 0.2 for a quick run
    "user_fraction": 1.0,
    "seed": 42,
    # split settings
    "test_days": 7,
    "val_days": 7,
    "gap_seconds": 30 * 60,
    # min listeners per song
    "min_item_users": 20,
    # model and eval settings
    "knn_k_grid": [20, 50, 100, 200],
    "ks": [10, 50],
    "tune_metric": "ndcg@10",
}
np.random.seed(CFG["seed"])
CFG["results_dir"].mkdir(parents=True, exist_ok=True)


def log(msg):
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)

### data
one row per user and song, using the first listen where more than 50% of the song was played

In [21]:
def download_raw(cfg):
    """download the listens file"""
    path = hf_hub_download(
        repo_id=cfg["hf_repo"],
        filename=cfg["hf_file"],
        repo_type="dataset",
        revision=cfg["hf_revision"],
        local_dir=cfg["raw_dir"],
    )
    return Path(path)


def build_pairs(raw_path, min_played_ratio_pct):
    """one row per user and song"""
    con = duckdb.connect()
    df = con.execute(
        """
        SELECT uid,
               item_id,
               min(timestamp)                       AS ts,
               arg_min(is_organic, timestamp)       AS is_organic,
               count(*)                             AS n_listens
        FROM read_parquet(?)
        WHERE played_ratio_pct > ?
        GROUP BY uid, item_id
        ORDER BY uid, ts, item_id
        """,
        [str(raw_path), min_played_ratio_pct],
    ).df()
    con.close()
    return df.astype({"uid": "int64", "item_id": "int64", "ts": "int64",
                      "is_organic": "int8", "n_listens": "int32"})


def sample_users(pairs, fraction, seed):
    """sample some users"""
    if fraction >= 1.0:
        return pairs
    users = np.sort(pairs["uid"].unique())
    rng = np.random.default_rng(seed)
    keep = rng.choice(users, size=max(1, int(round(len(users) * fraction))), replace=False)
    return pairs[pairs["uid"].isin(keep)].reset_index(drop=True)


def load_pairs(cfg):
    """load the pairs"""
    cache = cfg["processed_dir"] / f"pairs_played{cfg['min_played_ratio_pct']}.parquet"
    if cache.exists():
        pairs = pd.read_parquet(cache)
    else:
        raw = download_raw(cfg)
        pairs = build_pairs(raw, cfg["min_played_ratio_pct"])
        cache.parent.mkdir(parents=True, exist_ok=True)
        pairs.to_parquet(cache, index=False)
    return sample_users(pairs, cfg["user_fraction"], cfg["seed"])


log("loading pairs")
pairs = load_pairs(CFG)
log(f"{len(pairs):,} pairs, {pairs['uid'].nunique():,} users, {pairs['item_id'].nunique():,} songs")
pairs.head()

[19:00:17] loading pairs

[19:00:17] 9,019,829 pairs, 9,207 users, 630,139 songs

   uid  item_id     ts  is_organic  n_listens
0  100  1441281  39420           0          1
1  100  8326270  39420           0          4
2  100   286361  39625           0         10
3  100   732449  40110           0         29
4  100  7849270  40380           0          8

### split
global temporal split, same cutoff for every user:

`| inner train |gap| val (7d) |gap| test (7d) |`

- tuning: inner train -> val, used to pick k
- final: inner train + val -> test, the reported numbers

In [22]:
def temporal_splits(pairs, cfg):
    """split by time"""
    t_end = int(pairs["ts"].max()) + 1
    test_start = t_end - cfg["test_days"] * DAY
    val_start = test_start - cfg["gap_seconds"] - cfg["val_days"] * DAY

    def make(train_end, start, end):
        train = pairs[pairs["ts"] < train_end].reset_index(drop=True)
        test = pairs[(pairs["ts"] >= start) & (pairs["ts"] < end)].reset_index(drop=True)
        return {"train": train, "test": test, "train_end": train_end, "test_start": start, "test_end": end}

    tuning = make(val_start - cfg["gap_seconds"], val_start, test_start - cfg["gap_seconds"])
    final = make(test_start - cfg["gap_seconds"], test_start, t_end)
    return tuning, final


def build_dataset(split, min_item_users):
    """user x song matrix plus the held out songs for each user"""
    train = split["train"]
    item_users = train.groupby("item_id")["uid"].nunique()
    catalog = np.sort(item_users[item_users >= min_item_users].index.to_numpy())
    train = train[train["item_id"].isin(catalog)]

    user_ids = np.sort(train["uid"].unique())
    rows = np.searchsorted(user_ids, train["uid"].to_numpy())
    cols = np.searchsorted(catalog, train["item_id"].to_numpy())
    X = sp.csr_matrix((np.ones(len(rows), dtype=np.float32), (rows, cols)),
                      shape=(len(user_ids), len(catalog)))
    X.sum_duplicates()
    X.data[:] = 1.0
    popularity = np.asarray(X.sum(axis=0)).ravel()

    # only eval users that are in train
    test = split["test"][split["test"]["uid"].isin(user_ids)]
    grouped = test.groupby("uid")
    eval_uids = np.array(sorted(grouped.groups.keys()), dtype=np.int64)
    targets, organic = [], []
    for uid in eval_uids:
        g = grouped.get_group(uid)
        targets.append(set(g["item_id"].tolist()))
        organic.append(dict(zip(g["item_id"].tolist(), g["is_organic"].tolist())))
    in_catalog = np.isin(test["item_id"].to_numpy(), catalog).sum()

    return {
        "X": X, "user_ids": user_ids, "item_ids": catalog, "item_popularity": popularity,
        "eval_users": np.searchsorted(user_ids, eval_uids), "targets": targets, "target_organic": organic,
        "n_test_pairs_total": len(test), "n_test_pairs_in_catalog": int(in_catalog),
    }


def describe(name, split, ds):
    X = ds["X"]
    return {
        "split": name,
        "train_pairs": len(split["train"]), "train_users": int(split["train"]["uid"].nunique()),
        "heldout_pairs": len(split["test"]), "heldout_users": int(split["test"]["uid"].nunique()),
        "catalog_items": len(ds["item_ids"]), "matrix_users": X.shape[0], "matrix_nnz": int(X.nnz),
        "density_pct": round(100 * X.nnz / (X.shape[0] * X.shape[1]), 4),
        "eval_users": len(ds["eval_users"]),
        "eval_pairs": ds["n_test_pairs_total"],
        "eval_pairs_in_catalog_pct": round(100 * ds["n_test_pairs_in_catalog"] / max(ds["n_test_pairs_total"], 1), 2),
    }


tuning, final = temporal_splits(pairs, CFG)
ds_val = build_dataset(tuning, CFG["min_item_users"])
ds_test = build_dataset(final, CFG["min_item_users"])
data_summary = pd.DataFrame([describe("tuning (train -> val)", tuning, ds_val),
                             describe("final (train+val -> test)", final, ds_test)])
data_summary

,split,train_pairs,train_users,heldout_pairs,heldout_users,catalog_items,matrix_users,matrix_nnz,density_pct,eval_users,eval_pairs,eval_pairs_in_catalog_pct
0,tuning (train -> val),8456560,9190,285388,7357,66135,9155,6817677,1.1260,7336,284962,71.78
1,final (train+val -> test),8742509,9202,276856,7212,67931,9175,7069539,1.1343,7202,276702,72.92

### models
- **MostPopular** (naive): songs with the most listeners in train, same list for everyone
- **ItemKNN** (baseline): each song keeps its k most cosine similar songs. a song's score for a user is the sum of its similarity to the songs they listened to

neither model ever recommends a song the user already heard

In [23]:
def top_n_excluding_seen(scores, X_rows, n):
    """get top n, skip songs already heard"""
    seen_r, seen_c = X_rows.nonzero()
    scores[seen_r, seen_c] = -np.inf
    top = np.argpartition(-scores, kth=n - 1, axis=1)[:, :n]
    order = np.argsort(-np.take_along_axis(scores, top, axis=1), axis=1, kind="stable")
    return np.take_along_axis(top, order, axis=1)


class MostPopular:
    """most popular songs"""

    name = "MostPopular"

    def fit(self, X):
        self.X = X
        self.popularity = np.asarray(X.sum(axis=0)).ravel()
        self.order = np.argsort(-self.popularity, kind="stable")
        return self

    def recommend(self, user_rows, n):
        # skip songs the user already heard
        out = np.empty((len(user_rows), n), dtype=np.int64)
        for i, r in enumerate(user_rows):
            seen = self.X.indices[self.X.indptr[r]:self.X.indptr[r + 1]]
            candidates = self.order[: n + len(seen)]
            out[i] = candidates[~np.isin(candidates, seen)][:n]
        return out


class ItemKNN:
    """item knn with cosine similarity"""

    name = "ItemKNN-cosine"

    def __init__(self, k=100, n_jobs=4, working_memory_mb=256):
        self.k = k
        self.n_jobs = n_jobs
        self.working_memory_mb = working_memory_mb  # limit memory

    def fit(self, X):
        self.X = X
        items = X.T.tocsr()
        n_items = items.shape[0]
        k = min(self.k + 1, n_items)  # +1 for the item itself
        nn = NearestNeighbors(n_neighbors=k, metric="cosine", algorithm="brute", n_jobs=self.n_jobs)
        nn.fit(items)
        with config_context(working_memory=self.working_memory_mb):
            dist, idx = nn.kneighbors(items)
        sim = (1.0 - dist).astype(np.float32)

        rows = np.repeat(np.arange(n_items), k)
        cols, vals = idx.ravel(), sim.ravel()
        keep = (cols != rows) & (vals > 0)
        # similarity matrix
        self.S = sp.csr_matrix((vals[keep], (rows[keep], cols[keep])), shape=(n_items, n_items))
        pop = np.asarray(X.sum(axis=0)).ravel()
        self.tiebreak = (1e-6 * pop / pop.max()).astype(np.float32)
        return self

    def recommend(self, user_rows, n, batch=256):
        out = []
        for s in range(0, len(user_rows), batch):
            rows = user_rows[s:s + batch]
            Xr = self.X[rows]
            scores = (Xr @ self.S).toarray() + self.tiebreak
            out.append(top_n_excluding_seen(scores, Xr, n))
        return np.vstack(out)

### metrics and validation
precision, recall, ndcg, hit rate and catalog coverage at 10 and 50. every run is checked with `validate_recommendations` from the proposal section

In [24]:
def user_metrics(recs, targets, k):
    top = list(recs[:k])
    hits = np.array([item in targets for item in top], dtype=float)
    n_hits = hits.sum()
    discounts = 1.0 / np.log2(np.arange(2, k + 2))
    ideal = discounts[: min(len(targets), k)].sum()
    return {
        f"precision@{k}": n_hits / k,
        f"recall@{k}": n_hits / len(targets),
        f"ndcg@{k}": (hits * discounts[: len(top)]).sum() / ideal if ideal > 0 else 0.0,
        f"hitrate@{k}": float(n_hits > 0),
    }


def evaluate(rec_item_ids, targets, ks, n_catalog):
    """average metrics over users"""
    totals = {}
    for recs, tgt in zip(rec_item_ids, targets):
        for k in ks:
            for name, v in user_metrics(recs, tgt, k).items():
                totals[name] = totals.get(name, 0.0) + v
    result = {name: v / len(targets) for name, v in totals.items()}
    for k in ks:
        result[f"coverage@{k}"] = len(np.unique(rec_item_ids[:, :k])) / n_catalog
    return result


def check_recommendations(ds, rec_items, n_users=500):
    """run validate_recommendations on some users"""
    X = ds["X"]
    for r, items in zip(ds["eval_users"][:n_users], rec_items[:n_users]):
        heard = set(ds["item_ids"][X.indices[X.indptr[r]:X.indptr[r + 1]]].tolist())
        result = validate_recommendations(pd.DataFrame({"item_id": items}), heard)
        assert result == "Valid", result


def run_model(model, ds, cfg):
    t0 = time.time()
    model.fit(ds["X"])
    fit_s = time.time() - t0
    t0 = time.time()
    rec_idx = model.recommend(ds["eval_users"], max(cfg["ks"]))
    rec_s = time.time() - t0
    rec_items = ds["item_ids"][rec_idx]
    check_recommendations(ds, rec_items)
    metrics = evaluate(rec_items, ds["targets"], cfg["ks"], n_catalog=len(ds["item_ids"]))
    metrics.update(fit_seconds=round(fit_s, 1), recommend_seconds=round(rec_s, 1))
    return rec_idx, rec_items, metrics


# quick sanity check on a tiny made up example
_m = user_metrics(np.array([5, 1, 9]), {1, 2}, k=3)
assert _m["precision@3"] == 1 / 3 and _m["recall@3"] == 1 / 2 and _m["hitrate@3"] == 1.0
print("metrics ok")

metrics ok

### tune k on validation

In [25]:
tuning_rows = []
for k in CFG["knn_k_grid"]:
    log(f"validation: ItemKNN k={k}")
    _, _, m = run_model(ItemKNN(k=k), ds_val, CFG)
    tuning_rows.append({"model": "ItemKNN-cosine", "k": k, **m})
    log({x: round(float(y), 4) for x, y in m.items() if "@10" in x})
_, _, m = run_model(MostPopular(), ds_val, CFG)
tuning_rows.append({"model": "MostPopular", "k": None, **m})

tuning_df = pd.DataFrame(tuning_rows)
best_k = int(tuning_df.dropna(subset=["k"]).sort_values(CFG["tune_metric"], ascending=False).iloc[0]["k"])
log(f"best k = {best_k} by {CFG['tune_metric']}")
tuning_df

[19:00:29] validation: ItemKNN k=20

[19:02:25] {'precision@10': 0.0286, 'recall@10': 0.0116, 'ndcg@10': 0.031, 'hitrate@10': 0.178, 'coverage@10': 0.1254}

[19:02:25] validation: ItemKNN k=50

[19:04:17] {'precision@10': 0.0277, 'recall@10': 0.0107, 'ndcg@10': 0.0302, 'hitrate@10': 0.1715, 'coverage@10': 0.1088}

[19:04:17] validation: ItemKNN k=100

[19:06:14] {'precision@10': 0.0274, 'recall@10': 0.0107, 'ndcg@10': 0.0302, 'hitrate@10': 0.1716, 'coverage@10': 0.0996}

[19:06:14] validation: ItemKNN k=200

[19:08:13] {'precision@10': 0.0281, 'recall@10': 0.0106, 'ndcg@10': 0.031, 'hitrate@10': 0.1731, 'coverage@10': 0.0942}

[19:08:14] best k = 20 by ndcg@10

,model,k,precision@10,recall@10,ndcg@10,hitrate@10,precision@50,recall@50,ndcg@50,hitrate@50,coverage@10,coverage@50,fit_seconds,recommend_seconds
0,ItemKNN-cosine,20.0,0.028571,0.011564,0.031040,0.178026,0.023337,0.042583,0.036373,0.432116,0.125440,0.343661,109.0,6.7
1,ItemKNN-cosine,50.0,0.027726,0.010656,0.030240,0.171483,0.022568,0.039588,0.034569,0.399264,0.108778,0.289544,103.5,8.1
2,ItemKNN-cosine,100.0,0.027385,0.010724,0.030215,0.171619,0.021805,0.036861,0.033458,0.383451,0.099645,0.259046,106.1,10.0
3,ItemKNN-cosine,200.0,0.028094,0.010566,0.030952,0.173119,0.021336,0.036165,0.033257,0.377181,0.094247,0.239011,106.1,12.6
4,MostPopular,NaN,0.016317,0.007331,0.019053,0.099918,0.010883,0.019280,0.018429,0.219193,0.002283,0.005459,0.0,0.8

### baseline table (test)
refit on train + val and score once on the test week

In [26]:
final_rows, recs = [], {}
for model in [MostPopular(), ItemKNN(k=best_k)]:
    log(f"test: {model.name}")
    rec_idx, rec_items, m = run_model(model, ds_test, CFG)
    is_knn = isinstance(model, ItemKNN)
    label = model.name + (f" (k={best_k})" if is_knn else "")
    val_m = tuning_df[(tuning_df["model"] == model.name) &
                      ((tuning_df["k"] == best_k) if is_knn else tuning_df["k"].isna())].iloc[0]
    final_rows.append({"model": label, **m, "val_ndcg@10": val_m["ndcg@10"], "val_recall@10": val_m["recall@10"]})
    recs[label] = (rec_idx, rec_items)

table = pd.DataFrame(final_rows)
table_cols = ["model"] + [f"{m}@{k}" for k in CFG["ks"] for m in ["precision", "recall", "ndcg", "hitrate", "coverage"]]
table[table_cols].round(4)

[19:08:14] test: MostPopular

[19:08:15] test: ItemKNN-cosine

,model,precision@10,recall@10,ndcg@10,hitrate@10,coverage@10,precision@50,recall@50,ndcg@50,hitrate@50,coverage@50
0,MostPopular,0.0133,0.0067,0.0151,0.0878,0.0023,0.0092,0.0179,0.0158,0.2026,0.0054
1,ItemKNN-cosine (k=20),0.0272,0.0116,0.0299,0.1733,0.1169,0.0219,0.0427,0.0354,0.4218,0.3275

### diagnostics
breakdowns that help explain why the models differ: user activity, organic vs non organic songs, popularity bias, and overlap between the two models

In [27]:
def diagnostics(ds, results, k=10):
    """extra breakdowns"""
    out = {}
    hist = np.diff(ds["X"].indptr)[ds["eval_users"]]
    buckets = pd.qcut(hist, q=3, labels=["light", "medium", "heavy"])
    out["activity_bucket_train_items_range"] = {
        b: [int(hist[buckets == b].min()), int(hist[buckets == b].max())] for b in ["light", "medium", "heavy"]}

    pop_rank_pct = pd.Series(ds["item_popularity"]).rank(pct=True).to_numpy()
    head = pop_rank_pct >= 0.9

    rows = []
    for name, (rec_idx, rec_items) in results.items():
        per_user = [user_metrics(r, t, k) for r, t in zip(rec_items, ds["targets"])]
        ndcg = np.array([m[f"ndcg@{k}"] for m in per_user])
        hit = np.array([m[f"hitrate@{k}"] for m in per_user])
        row = {"model": name}
        for b in ["light", "medium", "heavy"]:
            row[f"ndcg@{k}_{b}"] = ndcg[buckets == b].mean()
            row[f"hitrate@{k}_{b}"] = hit[buckets == b].mean()
        for flag, label in [(1, "organic"), (0, "nonorganic")]:
            hits = total = 0
            for r, org in zip(rec_items, ds["target_organic"]):
                tgt = {i for i, o in org.items() if o == flag}
                if tgt:
                    hits += len(tgt.intersection(r[:k]))
                    total += len(tgt)
            row[f"recall@{k}_{label}_targets"] = hits / max(total, 1)
        top = rec_idx[:, :k]
        row[f"mean_pop_percentile@{k}"] = pop_rank_pct[top].mean()
        row[f"head10pct_share@{k}"] = head[top].mean()
        row[f"unique_items@{k}"] = int(len(np.unique(top)))
        rows.append(row)
    out["breakdown"] = rows

    names = list(results)
    if len(names) == 2:
        a, b = (results[n][0][:, :k] for n in names)
        jacc = [len(set(x) & set(y)) / len(set(x) | set(y)) for x, y in zip(a, b)]
        out[f"jaccard@{k}_{names[0]}_vs_{names[1]}"] = float(np.mean(jacc))
    return out


diag = diagnostics(ds_test, recs)
print(json.dumps({k: v for k, v in diag.items() if k != "breakdown"}, indent=2))
pd.DataFrame(diag["breakdown"]).set_index("model").T.round(4)

{
  "activity_bucket_train_items_range": {
    "light": [
      1,
      401
    ],
    "medium": [
      402,
      992
    ],
    "heavy": [
      993,
      6255
    ]
  },
  "jaccard@10_MostPopular_vs_ItemKNN-cosine (k=20)": 0.09788602615586521
}

model                         MostPopular  ItemKNN-cosine (k=20)
ndcg@10_light                      0.0213                 0.0420
hitrate@10_light                   0.1033                 0.2041
ndcg@10_medium                     0.0134                 0.0272
hitrate@10_medium                  0.0783                 0.1646
ndcg@10_heavy                      0.0108                 0.0203
hitrate@10_heavy                   0.0816                 0.1512
recall@10_organic_targets          0.0053                 0.0076
recall@10_nonorganic_targets       0.0027                 0.0069
mean_pop_percentile@10             0.9998                 0.9150
head10pct_share@10                 1.0000                 0.7951
unique_items@10                  154.0000              7944.0000

### save results

In [28]:
out = CFG["results_dir"]
table.to_csv(out / "baseline_table.csv", index=False)
with open(out / "baseline_table.md", "w") as f:
    f.write(table[table_cols].to_markdown(index=False, floatfmt=".4f"))
tuning_df.to_csv(out / "knn_tuning_validation.csv", index=False)
data_summary.to_csv(out / "data_summary.csv", index=False)
pd.DataFrame(diag["breakdown"]).to_csv(out / "diagnostics_breakdown.csv", index=False)
with open(out / "diagnostics.json", "w") as f:
    json.dump(diag, f, indent=2, default=float)

# example output in the uid, rank, item_id format
sample_rows = []
for label, (_, rec_items) in recs.items():
    for u, items in zip(ds_test["user_ids"][ds_test["eval_users"][:5]], rec_items[:5, :10]):
        sample_rows += [{"model": label, "uid": int(u), "rank": i + 1, "item_id": int(it)} for i, it in enumerate(items)]
pd.DataFrame(sample_rows).to_csv(out / "sample_recommendations.csv", index=False)

with open(out / "run_config.json", "w") as f:
    json.dump({"config": {k: str(v) if isinstance(v, Path) else v for k, v in CFG.items()},
               "best_k": best_k, "python": platform.python_version(), "platform": platform.platform(),
               "versions": {"numpy": np.__version__, "pandas": pd.__version__, "scipy": scipy.__version__,
                            "scikit-learn": sklearn.__version__, "duckdb": duckdb.__version__}}, f, indent=2)
log(f"results written to {out}")

[19:10:12] results written to C:\Users\Arbab\OneDrive\Desktop\Projects\ml_class_proj\results